name: Auto commit
on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/25 * * * *'
    
jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Test the jobs
        run: |
          git config --global user.email "idamasitoh34@gmail.com"
          git config --global user.name "idamasitoh34"
          git commit -am tod --allow-empty; git push -u origin main;
